version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    steps:
      - setup_remote_docker
      - run:
          name: Login to Dockerhub
          command: docker login --username loganjhennessy --password $DOCKER_PASS
      - run:
          name: Build infrastructure image
          command: docker build --file infra/Dockerfile --tag loganjhennessy/gcp-infra-config-python:$CIRCLE_BRANCH
      - run:
          name: Push infrastructure image
          command: docker push loganjhennessy/gcp-infra-config-python:$CIRCLE_BRANCH

  push:
    docker:
      - image: python:3.8.2-buster

workflows:
  main:
    jobs:
      - build


#  test:
#    steps:
#      - checkout
#      - python/load-cache
#      - python/install-deps
#      - python/save-cache
#      - run:
#          command: ./manage.py test
#          name: Test

# docker tag local-image:tagname new-repo:tagname
# docker push new-repo:tagname
