workflows:
  version: 2
  main:
    jobs:
      sync-infrastructure:
        docker:
          - image: python:3.8.2-slim-buster
        requires: hold
        steps:
          - run: python infra/deploy.py