version: 2
jobs:
  sync-infrastructure:
    docker:
      - image: python:3.8.2-slim-buster
    steps:
      - checkout
      - run: pip install infra/requirements.txt
      - run: python infra/deploy.py

workflows:
  version: 2
  main:
    jobs:
      - sync-infrastructure